      
name: Web CI/CD Workflow

on: 
  push:
    branches: 
      - developpe
    paths:
      - 'web/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'web/**'

jobs:
  build-and-test-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    - name: Install dependencies for Web project
      run: npm ci
      working-directory: web
    - name: Build Web project
      run: npm run build --if-present
      working-directory: web
    - name: Test Web project
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      working-directory: web
